/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto;

import proyectoimportar.ClasePrueba;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        ClasePrueba p=new ClasePrueba();
        System.out.println("Usando la dependencia importada: "+p.abreviarCadena("Hola como andas",5));
    }
}
